name: Docker Image RabbitMQ
on:
  schedule:
    - cron: "0 6 1 * *"   # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/rabbitmq/**
    branches:
      - multi-arch
jobs:
  rabbitmq:
    name: RabbitMQ

    strategy:
      fail-fast: false
      matrix:
        version: ['3.7', '3.8']
        multiarch: ['true']

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (amd64, arm64)
        uses: docker/build-push-action@v2
        if: ${{ matrix.multiarch == 'true' }}
        with:
          file: images/rabbitmq/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rabbitmq:${{ matrix.version }}

      - name: Build and push (amd64 only)
        uses: docker/build-push-action@v2
        if: ${{ matrix.multiarch == 'false' }}
        with:
          file: images/rabbitmq/${{ matrix.version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rabbitmq:${{ matrix.version }}